<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ca63d411-9c48-4eaf-821e-20f41b4440f4</elementGuidId>
    <imagePath></imagePath>
    <name>button_tiepTheo2</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ud-btn\ ud-btn-medium\ ud-btn-white-solid\ ud-btn-round\ ud-btn-text-sm\ ud-btn-icon\ ud-btn-icon-medium\ ud-btn-icon-round\ ud-carousel-pager-button\ ud-carousel-pager-button-next\ enriched-skills_slide-indicator-pager__QuFAy\ carousel_button__mtsms\ carousel_next-button__6VcuP"] &gt; [role="img"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[2]/div[1]/button[2]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@role,'img')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.enriched-skills_pager-buttons-wrapper__5ghl8 &gt; button:nth-child(3)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ud-icon ud-icon-large ud-icon-bi-directional</value>
        <webElementGuid>adda66f6-a5bb-4aad-8c46-9532c24e5210</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>img</value>
        <webElementGuid>adda66f6-a5bb-4aad-8c46-9532c24e5210</webElementGuid>
    </webElementProperties>
</WebElementEntity>