<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9be295a3-7fb1-436b-ac19-440343f8474f</elementGuidId>
    <imagePath></imagePath>
    <name>button_explore</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="popper-trigger--6"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/header[1]/nav[2]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"desktop-header\"] #popper-trigger--6</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ud-btn ud-btn-medium ud-btn-ghost ud-btn-text-sm js-header-button desktop-header_dropdown-button__UHrW7</value>
        <webElementGuid>adda66f6-a5bb-4aad-8c46-9532c24e5210</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Khám phá</value>
        <webElementGuid>adda66f6-a5bb-4aad-8c46-9532c24e5210</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>adda66f6-a5bb-4aad-8c46-9532c24e5210</webElementGuid>
    </webElementProperties>
</WebElementEntity>