<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5b1706aa-4307-4c25-8f6d-fb9d182aea5c</elementGuidId>
    <imagePath></imagePath>
    <name>div_lohpBody</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="layout_content__wSshz"] &gt; div</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"lohp-body\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>lohp-body</value>
        <webElementGuid>adda66f6-a5bb-4aad-8c46-9532c24e5210</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Các khóa học có giá từ 309.000 ₫
        
        Định hình cơ hội nghề nghiệp của bạn với kỹ năng lãnh đạo và AI. Ưu đãi kết thúc vào ngày {{date_time}}
        
        Tiết kiệm ngay
        ...[truncated lines=117]</value>
        <webElementGuid>adda66f6-a5bb-4aad-8c46-9532c24e5210</webElementGuid>
    </webElementProperties>
</WebElementEntity>