<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_nestedTextLocatorPoc</name>
   <tag></tag>
   <elementGuidId>7208a2ef-bad3-4ebd-887e-a3d5db8be4bb</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/nav[1]/div[3]/ul[1]/li[13]/a[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) li:nth-of-type(13) > .flex</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/nested-text-locator-poc' and (text() = 'Nested Text Locator POC' or . = 'Nested Text Locator POC')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;nav-nested-text-locator-poc&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center px-3 py-2 text-sm rounded-md text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700</value>
      <webElementGuid>dd118440-415f-48c2-9705-d15f6805ad69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/nested-text-locator-poc</value>
      <webElementGuid>dd118440-415f-48c2-9705-d15f6805ad69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nested Text Locator POC</value>
      <webElementGuid>dd118440-415f-48c2-9705-d15f6805ad69</webElementGuid>
   </webElementProperties>
</WebElementEntity>
