<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_selectNestedTextOption</name>
   <tag></tag>
   <elementGuidId>31493822-2849-4896-9b09-afc3adbcf061</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/div[1]/div[2]/ul[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;cursor-pointer\ rounded-xl\ border\ border-gray-300\ bg-white\ px-4\ py-3\ outline-none\ hover\:border-blue-400\ hover\:bg-blue-50\ focus\:border-blue-500\ focus\:ring-2\ focus\:ring-blue-200\ dark\:border-gray-600\ dark\:bg-gray-800\ dark\:hover\:bg-gray-800&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'CHILD SPAN ONLY
         Nested Text Option' or . = 'CHILD SPAN ONLY
         Nested Text Option') and @role = 'option']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> nth=26</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer rounded-xl border border-gray-300 bg-white px-4 py-3 outline-none hover:border-blue-400 hover:bg-blue-50 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 dark:border-gray-600 dark:bg-gray-800 dark:hover:bg-gray-800</value>
      <webElementGuid>dd118440-415f-48c2-9705-d15f6805ad69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>dd118440-415f-48c2-9705-d15f6805ad69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHILD SPAN ONLY
      Nested Text Option</value>
      <webElementGuid>dd118440-415f-48c2-9705-d15f6805ad69</webElementGuid>
   </webElementProperties>
</WebElementEntity>
