<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_targetChildSpanText</name>
   <tag></tag>
   <elementGuidId>bfa6dd68-1d73-4b82-a179-64672ac60c0c</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/aside[1]/div[2]/div[1]/div[2]/div[2]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) &gt; [class="space-y-3"] &gt; div:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.space-y-3 &gt; div:nth-child(3) &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-xl border p-3 text-sm border-rose-300 bg-rose-50 dark:border-rose-700 dark:bg-rose-950/20</value>
      <webElementGuid>37c1589f-6609-4532-a1b3-65ebce8f4e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Target child span text
      matches: 0
      //*[@data-poc='nested-title-option' and @role='option'][.//span[normalize-space()='Nested Text Option']]</value>
      <webElementGuid>37c1589f-6609-4532-a1b3-65ebce8f4e4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
