<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>item_relationshipManagementOption</name>
   <tag></tag>
   <elementGuidId>ce0186ae-2727-49e0-bcc2-85ef11be13d8</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/div[1]/div[3]/nav[1]/ul[1]/li[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.list-none</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Relationship Management / Customer Relationship Management / Account
         Accounts - CRM' or . = 'Relationship Management / Customer Relationship Management / Account
         Accounts - CRM') and @role = 'option']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>main nav li</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-none cursor-pointer rounded-xl border border-gray-300 bg-white p-2 outline-none hover:border-blue-400 focus:ring-2 focus:ring-blue-200 dark:border-gray-700 dark:bg-gray-800 dark:focus:ring-blue-900/60</value>
      <webElementGuid>822a0c58-f972-4700-8c2e-cd5469c26303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>822a0c58-f972-4700-8c2e-cd5469c26303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Relationship Management / Customer Relationship Management / Account
      Accounts - CRM</value>
      <webElementGuid>822a0c58-f972-4700-8c2e-cd5469c26303</webElementGuid>
   </webElementProperties>
</WebElementEntity>
