<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>item_directTextOption</name>
   <tag></tag>
   <elementGuidId>b36722d7-0348-4a80-bfe5-38f00e9b0277</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/div[1]/div[1]/ul[1]/li[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;cursor-pointer\ rounded-xl\ border\ border-gray-300\ bg-white\ px-4\ py-3\ text-sm\ font-medium\ text-gray-900\ outline-none\ hover\:border-blue-400\ hover\:bg-blue-50\ focus\:border-blue-500\ focus\:ring-2\ focus\:ring-blue-200\ dark\:border-gray-600\ dark\:bg-gray-800\ dark\:text-white\ dark\:hover\:bg-gray-800&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Direct Text Option' or . = 'Direct Text Option') and @role = 'option']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:text=&quot;Direct Text Option&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer rounded-xl border border-gray-300 bg-white px-4 py-3 text-sm font-medium text-gray-900 outline-none hover:border-blue-400 hover:bg-blue-50 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:hover:bg-gray-800</value>
      <webElementGuid>75bf4f85-18f9-460e-9235-c2d8fe8022ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>75bf4f85-18f9-460e-9235-c2d8fe8022ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Direct Text Option</value>
      <webElementGuid>75bf4f85-18f9-460e-9235-c2d8fe8022ac</webElementGuid>
   </webElementProperties>
</WebElementEntity>
