<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_dynamicIdlocator</name>
   <tag></tag>
   <elementGuidId>f56e1720-1757-400c-8d95-6f09a795faf2</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/nav[1]/div[3]/ul[1]/li[14]/a[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(14) > .flex</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/dynamic-id-locator' and (text() = 'Dynamic ID Locator' or . = 'Dynamic ID Locator')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;nav-dynamic-id-locator&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center px-3 py-2 text-sm rounded-md text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700</value>
      <webElementGuid>dd118440-415f-48c2-9705-d15f6805ad69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dynamic-id-locator</value>
      <webElementGuid>dd118440-415f-48c2-9705-d15f6805ad69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dynamic ID Locator</value>
      <webElementGuid>dd118440-415f-48c2-9705-d15f6805ad69</webElementGuid>
   </webElementProperties>
</WebElementEntity>
