<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>main_nestedTextLocatorPoc</name>
   <tag></tag>
   <elementGuidId>4b3d2b80-b909-4a50-8272-ed8c983dfde0</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'NESTED TEXT LOCATOR POC
         Captured objects with nested text
         
         This page reproduces the failure mode where a recorder targets a parent interactive element but uses a direct text()='...' predicate even though the visible label is rendered by nested child nodes.
         
         ...[truncated lines=70]')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="p-4\ md\:p-6"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>main</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-4 md:p-6</value>
      <webElementGuid>642d05a1-8ce6-48f7-9cc9-bc0470e38d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NESTED TEXT LOCATOR POC
      Captured objects with nested text
      
      This page reproduces the failure mode where a recorder targets a parent interactive element but uses a direct text()='...' predicate even though the visible label is rendered by nested child nodes.
      
      ...[truncated lines=70]</value>
      <webElementGuid>642d05a1-8ce6-48f7-9cc9-bc0470e38d4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
