<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>span_normalizedDescendantTextPredicate</name>
   <tag></tag>
   <elementGuidId>7078370c-f181-4032-94a1-4c9b2bb26558</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/aside[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'Normalized descendant text predicate')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(1) &gt; [class="space-y-3"] &gt; div:nth-of-type(2) &gt; .flex &gt; .font-medium</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) &gt; .mb-1 &gt; .font-medium &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-medium text-gray-900 dark:text-white</value>
      <webElementGuid>fe795cb9-2adf-441a-8218-7ee55fee8508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Normalized descendant text predicate</value>
      <webElementGuid>fe795cb9-2adf-441a-8218-7ee55fee8508</webElementGuid>
   </webElementProperties>
</WebElementEntity>
