<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_dynamicIdlocatorIssue</name>
   <tag></tag>
   <elementGuidId>d00f2a8b-50ec-4a13-a043-c8ef544a6ff6</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;p-8\ max-w-6xl\ mx-auto&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Dynamic ID Locator - Issue Reproduction &amp; Fix
         Issue Description
         
         Dynamic IDs are identifiers that change across sessions or builds, typically following patterns like:
         
         ...[truncated lines=103]' or . = 'Dynamic ID Locator - Issue Reproduction &amp; Fix
         Issue Description
         
         Dynamic IDs are identifiers that change across sessions or builds, typically following patterns like:
         
         ...[truncated lines=103]')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> nth=17</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-8 max-w-6xl mx-auto</value>
      <webElementGuid>5f6633c2-0476-47f7-b3a8-f7af77a8d63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dynamic ID Locator - Issue Reproduction &amp; Fix
      Issue Description
      
      Dynamic IDs are identifiers that change across sessions or builds, typically following patterns like:
      
      ...[truncated lines=103]</value>
      <webElementGuid>5f6633c2-0476-47f7-b3a8-f7af77a8d63d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
