<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d2fa5957-593e-428a-af07-4d55a8193272</elementGuidId>
    <imagePath></imagePath>
    <name>label_generativeAi</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[for="checkbox--486"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[2]/div[9]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>label &gt;&gt; internal:text=\"Generative AI (GenAI)(238)\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ud-toggle-input-container ud-text-sm</value>
        <webElementGuid>ac3efb9d-8f6d-48a6-b673-df8641f8e2f8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Generative AI (GenAI)
        (238)</value>
        <webElementGuid>ac3efb9d-8f6d-48a6-b673-df8641f8e2f8</webElementGuid>
    </webElementProperties>
</WebElementEntity>