<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ecfff7e4-11fd-44f1-aacc-759e208ded63</elementGuidId>
    <imagePath></imagePath>
    <name>link_propertyDetails</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[7]/div[1]/div[2]/div[4]/div[1]/div[1]/article[2]/h3[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'{{address}} chuyển đổi gần 5.000 m2 đất {{name}} là{{name}}, khách sạn')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a[title=\"{{address}} chuy\u1ec3n \u0111\u1ed5i g\u1ea7n 5\\.000 m2 \u0111\u1ea5t {{address}} l\u00e0m{{name}}, kh\u00e1ch s\u1ea1n\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}{{url}}</value>
        <webElementGuid>b1fca37d-a0df-41fa-9639-39240fef6512</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>{{address}} chuyển đổi gần 5.000 m2 đất {{address}} là{{name}}, khách sạn</value>
        <webElementGuid>b1fca37d-a0df-41fa-9639-39240fef6512</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>{{address}} chuyển đổi gần 5.000 m2 đất {{name}} là{{name}}, khách sạn</value>
        <webElementGuid>b1fca37d-a0df-41fa-9639-39240fef6512</webElementGuid>
    </webElementProperties>
</WebElementEntity>