<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_goods</name>
   <tag></tag>
   <elementGuidId>aea9e801-7930-4494-add5-2a2cdc1567fa</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[5]/div[1]/nav[1]/div[1]/div[2]/ul[1]/li[8]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Hàng hóa')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.scroll &gt; li:nth-of-type(8) &gt; a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a[title="Hàng hóa"] &gt;&gt; nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/kinh-doanh/hang-hoa</value>
      <webElementGuid>729c1c9c-bc4b-4a6d-9590-7fe0836b023f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hàng hóa</value>
      <webElementGuid>729c1c9c-bc4b-4a6d-9590-7fe0836b023f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Hàng hóa</value>
      <webElementGuid>729c1c9c-bc4b-4a6d-9590-7fe0836b023f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
