<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>code_directTextOptionXpath2</name>
   <tag></tag>
   <elementGuidId>bf9a47d9-9bb6-452e-bec6-76b6460e9fbf</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/aside[1]/div[2]/div[1]/div[1]/div[2]/div[2]/code[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'//*[@data-poc='direct-text-option' and @role='option' and normalize-space(.)='Direct Text Option']')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(1) &gt; [class="space-y-3"] &gt; div:nth-of-type(2) &gt; .block</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) &gt; .block &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block overflow-x-auto whitespace-pre-wrap break-all rounded bg-gray-100 p-2 text-xs text-gray-800 dark:bg-gray-800 dark:text-gray-200</value>
      <webElementGuid>fe795cb9-2adf-441a-8218-7ee55fee8508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>//*[@data-poc='direct-text-option' and @role='option' and normalize-space(.)='Direct Text Option']</value>
      <webElementGuid>fe795cb9-2adf-441a-8218-7ee55fee8508</webElementGuid>
   </webElementProperties>
</WebElementEntity>
