<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_nestedTextOnly2</name>
   <tag></tag>
   <elementGuidId>f06e6c33-e426-4cb6-912b-756d3d0ecc6e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/div[1]/div[2]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'Nested text only
         
         Primary repro: the visible label lives in a child span, while the parent role element has no direct text node.')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="rounded-2xl\ border\ p-5\ shadow-sm\ transition\ border-blue-500\ bg-blue-50\/60\ dark\:border-blue-400\ dark\:bg-blue-950\/30"] &gt; .flex &gt; div</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) &gt; .mb-4 &gt; div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nested text only
      
      Primary repro: the visible label lives in a child span, while the parent role element has no direct text node.</value>
      <webElementGuid>fe795cb9-2adf-441a-8218-7ee55fee8508</webElementGuid>
   </webElementProperties>
</WebElementEntity>
