<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_directTextOnParent</name>
   <tag></tag>
   <elementGuidId>daf9398b-2aed-4734-ac85-b0f39ce6625c</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'Direct text on parent
         
         Control case: the role element owns the text node directly, so text() should still work.
         
         role="option"
         ...[truncated lines=20]')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.grid &gt; div</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.space-y-5 &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>space-y-5</value>
      <webElementGuid>fe795cb9-2adf-441a-8218-7ee55fee8508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Direct text on parent
      
      Control case: the role element owns the text node directly, so text() should still work.
      
      role="option"
      ...[truncated lines=20]</value>
      <webElementGuid>fe795cb9-2adf-441a-8218-7ee55fee8508</webElementGuid>
   </webElementProperties>
</WebElementEntity>
