<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_directTextOnParent3</name>
   <tag></tag>
   <elementGuidId>d13f4f40-261c-46cd-aa89-adfea24abc1d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.grid &gt; div &gt; div:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.space-y-5 &gt; div &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-2xl border p-5 shadow-sm transition border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-900</value>
      <webElementGuid>37c1589f-6609-4532-a1b3-65ebce8f4e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Direct text on parent
      
      Control case: the role element owns the text node directly, so text() should still work.
      
      role="option"
      ...[truncated lines=6]</value>
      <webElementGuid>37c1589f-6609-4532-a1b3-65ebce8f4e4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
