<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_nestedTextOnly2_1</name>
   <tag></tag>
   <elementGuidId>81771209-b5d3-4b2e-b82f-7d1634836ba8</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/div[1]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'Nested text only
         
         Primary repro: the visible label lives in a child span, while the parent role element has no direct text node.
         
         role="option"
         ...[truncated lines=7]')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="rounded-2xl\ border\ p-5\ shadow-sm\ transition\ border-blue-500\ bg-blue-50\/60\ dark\:border-blue-400\ dark\:bg-blue-950\/30"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div &gt;&gt; nth=23</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-2xl border p-5 shadow-sm transition border-blue-500 bg-blue-50/60 dark:border-blue-400 dark:bg-blue-950/30</value>
      <webElementGuid>642d05a1-8ce6-48f7-9cc9-bc0470e38d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nested text only
      
      Primary repro: the visible label lives in a child span, while the parent role element has no direct text node.
      
      role="option"
      ...[truncated lines=7]</value>
      <webElementGuid>642d05a1-8ce6-48f7-9cc9-bc0470e38d4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
