<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_targetTitleDescendant</name>
   <tag></tag>
   <elementGuidId>802f43f3-878c-4951-b90c-8848b818c028</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/aside[1]/div[2]/div[1]/div[3]/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'Target title descendant
         matches: 0
         //*[@data-poc='nested-title-subtitle-option' and @role='option'][.//span[normalize-space()='Accounts - CRM']]')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) &gt; [class="space-y-3"] &gt; div:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div &gt;&gt; nth=54</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-xl border p-3 text-sm border-rose-300 bg-rose-50 dark:border-rose-700 dark:bg-rose-950/{{url}}</value>
      <webElementGuid>642d05a1-8ce6-48f7-9cc9-bc0470e38d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Target title descendant
      matches: 0
      //*[@data-poc='nested-title-subtitle-option' and @role='option'][.//span[normalize-space()='Accounts - CRM']]</value>
      <webElementGuid>642d05a1-8ce6-48f7-9cc9-bc0470e38d4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
