<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_brokenParentTextPredicate</name>
   <tag></tag>
   <elementGuidId>1e41509d-df11-44db-8409-86a4e7edee0e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/aside[1]/div[2]/div[1]/div[2]/div[2]/div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'Broken parent text() predicate
         matches: 0
         //*[@data-poc='nested-title-option' and @role='option' and text()='Nested Text Option']')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) &gt; [class="space-y-3"] &gt; div:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.space-y-5 &gt; div:nth-child(2) &gt; .space-y-3 &gt; div &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>{{url}} dark{{url}} dark{{url}}</value>
      <webElementGuid>fe795cb9-2adf-441a-8218-7ee55fee8508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Broken parent text() predicate
      matches: 0
      //*[@data-poc='nested-title-option' and @role='option' and text()='Nested Text Option']</value>
      <webElementGuid>fe795cb9-2adf-441a-8218-7ee55fee8508</webElementGuid>
   </webElementProperties>
</WebElementEntity>
