<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>header_capturedObjects</name>
   <tag></tag>
   <elementGuidId>e7875dfd-eed1-46e2-be8f-73b40dc49ab3</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/header[1]/h1[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'Captured objects with nested text')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.font-bold</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>h1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-3xl font-bold text-gray-900 dark:text-white</value>
      <webElementGuid>fe795cb9-2adf-441a-8218-7ee55fee8508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Captured objects with nested text</value>
      <webElementGuid>fe795cb9-2adf-441a-8218-7ee55fee8508</webElementGuid>
   </webElementProperties>
</WebElementEntity>
