<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>item_compareXpath</name>
   <tag></tag>
   <elementGuidId>f57cc451-3aab-487e-b2bb-7ae78872150e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[1]/ol[1]/li[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'Compare the recorded XPath with the on-page check table to see whether it behaves like the broken parent-text form or a descendant-safe form.')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.list-decimal &gt; li:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>ol li &gt;&gt; nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compare the recorded XPath with the on-page check table to see whether it behaves like the broken parent-text form or a descendant-safe form.</value>
      <webElementGuid>7ae7c4c9-b348-41ff-8662-fba5bc469bdf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
