<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>item_nestedTitleOption</name>
   <tag></tag>
   <elementGuidId>37a5ea83-552c-4f04-86b3-ed9c3a545f48</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/div[1]/div[2]/ul[1]/li[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@data-testid,'nested-title-option') and equals(@text,'CHILD SPAN ONLY
               Nested Text Option') and equals(@role,'option')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="cursor-pointer\ rounded-xl\ border\ border-gray-300\ bg-white\ px-4\ py-3\ outline-none\ hover\:border-blue-400\ hover\:bg-blue-50\ focus\:border-blue-500\ focus\:ring-2\ focus\:ring-blue-200\ dark\:border-gray-600\ dark\:bg-gray-800\ dark\:hover\:bg-gray-800"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid="nested-title-option"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer rounded-xl border border-gray-300 bg-white px-4 py-3 outline-none hover:border-blue-400 hover:bg-blue-50 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 dark:border-gray-600 dark:bg-gray-800 dark:hover:bg-gray-800</value>
      <webElementGuid>7ae7c4c9-b348-41ff-8662-fba5bc469bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>nested-title-option</value>
      <webElementGuid>7ae7c4c9-b348-41ff-8662-fba5bc469bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7ae7c4c9-b348-41ff-8662-fba5bc469bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHILD SPAN ONLY
            Nested Text Option</value>
      <webElementGuid>7ae7c4c9-b348-41ff-8662-fba5bc469bdf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
