<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>main_nestedTextLocatorPoc</name>
   <tag></tag>
   <elementGuidId>d0b98990-cdad-4ea2-8a96-4fb0d29fcd37</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="p-4\ md\:p-6"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>main</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>{{password}}</value>
      <webElementGuid>37c1589f-6609-4532-a1b3-65ebce8f4e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NESTED TEXT LOCATOR POC
      Captured objects with nested text
      
      This page reproduces the failure mode where a recorder targets a parent interactive element but uses a direct text()='...' predicate even though the visible label is rendered by nested child nodes.
      
      ...[truncated lines=70]</value>
      <webElementGuid>37c1589f-6609-4532-a1b3-65ebce8f4e4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
