<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>section_howToUse</name>
   <tag></tag>
   <elementGuidId>0edfa459-5ce2-4418-82b2-fd55f5068741</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'How to use this page
         Open this page in the AUT test app and record clicks on each card.
         Inspect the emitted primary XPath for the selected target.
         Compare the recorded XPath with the on-page check table to see whether it behaves like the broken parent-text form or a descendant-safe form.')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="mx-auto\ max-w-7xl\ space-y-8\ p-6"] &gt; .border</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-2xl border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-900</value>
      <webElementGuid>642d05a1-8ce6-48f7-9cc9-bc0470e38d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How to use this page
      Open this page in the AUT test app and record clicks on each card.
      Inspect the emitted primary XPath for the selected target.
      Compare the recorded XPath with the on-page check table to see whether it behaves like the broken parent-text form or a descendant-safe form.</value>
      <webElementGuid>642d05a1-8ce6-48f7-9cc9-bc0470e38d4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
