<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_automatedTesting</name>
   <tag></tag>
   <elementGuidId>e6415115-60ee-4b6f-8c45-de36e60b260d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/div[1]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.about-section</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.et_builder_inner_content &gt; div:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_section et_pb_section_2 about-section et_pb_with_background et_section_regular</value>
      <webElementGuid>ce1f0dd8-bbee-4f26-b90f-7447e68c7389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leading the World In Automated Testing
      
      Ultimate QA is your one-stop solution for all your automated software testing needs. We offer comprehensive consulting services for enterprises and top-notch training programs for individuals, ensuring success for both organizations and professionals in the world of software testing automation.
      
      For Enterprises:
      ...[truncated lines=19]</value>
      <webElementGuid>ce1f0dd8-bbee-4f26-b90f-7447e68c7389</webElementGuid>
   </webElementProperties>
</WebElementEntity>
