<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>main_object</name>
   <tag></tag>
   <elementGuidId>bf40f59e-591d-437b-9503-0c8935421f04</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main-content-anchor</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#main-content-anchor</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>layout_content__wSshz</value>
      <webElementGuid>e1f0ae28-103a-495a-ab4f-10c1827c8638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main-content-anchor</value>
      <webElementGuid>e1f0ae28-103a-495a-ab4f-10c1827c8638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Communication Skills Courses
      
      Communication skills courses teach effective information conveyance, active listening, clear articulation, and persuasive communication. Developing these skills is crucial for professionals in any industry to improve team dynamics and personal interactions.
      
      Items 1, 2, 3, 4 of 4
      ...[truncated lines=73]</value>
      <webElementGuid>e1f0ae28-103a-495a-ab4f-10c1827c8638</webElementGuid>
   </webElementProperties>
</WebElementEntity>
