<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_policyHolderDobField</name>
   <tag></tag>
   <elementGuidId>a7787689-66d2-41c1-aceb-072b6c995c2a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-customer-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/app-customer-search[1]/form[1]/div[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.customer-search > div:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'and the policy holder's date of birth is******1963' or . = 'and the policy holder's date of birth is******1963')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> nth=84</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-field row</value>
      <webElementGuid>5ac09ad8-769a-43b4-9158-eddcdd89760e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>and the policy holder's date of birth is******1963</value>
      <webElementGuid>5ac09ad8-769a-43b4-9158-eddcdd89760e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
