<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>matIcon_object3</name>
   <tag></tag>
   <elementGuidId>3dcb6420-53f8-4ea9-98e9-78c4aedc6baf</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-hospitalization-benetifs[1]/div[1]/div[2]/div[1]/esub-daterange-picker[1]/div[1]/div[1]/div[1]/div[1]/cds-calendar[1]/cds-calendar-header[1]/div[1]/section[1]/cds-icon[1]/mat-icon[1]/*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;cds-icon\ cds-calendar-previous\ default&quot;] [id=&quot;Layer_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Layer_1 >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Layer_1</value>
      <webElementGuid>5ac09ad8-769a-43b4-9158-eddcdd89760e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
