<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>matRadioGroup_claimCauseRadioGroup</name>
   <tag></tag>
   <elementGuidId>f42ef625-7d6c-44db-84ea-eb49cd86937f</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-claim-event[1]/div[1]/div[1]/app-claim-event-cause[1]/div[1]/div[1]/app-radio-button[1]/cds-radio[1]/mat-radio-group[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[id=&quot;cds-radio-2&quot;] > .mat-mdc-radio-group</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'AccidentMedical Condition (Please select for dental and illness)' or . = 'AccidentMedical Condition (Please select for dental and illness)') and @role = 'radiogroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cds-radio-2 mat-radio-group</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-radio-group ng-valid ng-touched ng-dirty</value>
      <webElementGuid>5ac09ad8-769a-43b4-9158-eddcdd89760e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radiogroup</value>
      <webElementGuid>5ac09ad8-769a-43b4-9158-eddcdd89760e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AccidentMedical Condition (Please select for dental and illness)</value>
      <webElementGuid>5ac09ad8-769a-43b4-9158-eddcdd89760e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
