<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>329a6d70-92c2-49cd-935c-9136b35d63db</elementGuidId>
    <imagePath></imagePath>
    <name>link_logo</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="desktop-header-module--flex-middle--k0Teb\ desktop-header-module--logo--AwnFF"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/header[1]/a[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>header &gt; .desktop-header-module--flex-middle--k0Teb</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>desktop-header-module--flex-middle--{{password}} desktop-header-module--logo--{{secret_key}}</value>
        <webElementGuid>ac3efb9d-8f6d-48a6-b673-df8641f8e2f8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/</value>
        <webElementGuid>ac3efb9d-8f6d-48a6-b673-df8641f8e2f8</webElementGuid>
    </webElementProperties>
</WebElementEntity>