<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_boxCategory</name>
   <tag></tag>
   <elementGuidId>96c6fe3b-6da1-4d8e-876c-82c36651f1ab</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[9]/div[1]/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.wrapper-sticky</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#automation_HV1 &gt; div:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>width_common wrapper-sticky box-category</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phát triển kinh tế tư nhân
      Thủ tướng: Tạo điều kiện khi doanh nghiệp tư nhân tham gia các dự án lớn 18
      Bộ Chính trị yêu cầu sớm triển khai dự án điện hạt nhân Ninh Thuận 1&amp;2 
      Số doanh nghiệp thành lập sau Nghị quyết 68 cao kỷ lục  48</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
