<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_novaland</name>
   <tag></tag>
   <elementGuidId>2626a057-43da-4759-b2c6-67bd7faace92</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[6]/div[1]/div[1]/div[1]/div[1]/article[3]/div[1]/h3[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Novaland được hoàn nhập hơn 3.300 tỷ đồng tiền sử dụng đất dự án Lakeview City')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>article:nth-of-type(3) &gt; .thumb-art &gt; .title-news &gt; a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a &gt;&gt; internal:text="Novaland được hoàn nhập hơn 3.300 tỷ đồng tiền sử dụng đất dự án Lakeview City"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>{{url}}</value>
      <webElementGuid>cb65ce20-8b3f-4c0a-a384-95461ecd465c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Novaland được hoàn nhập hơn 3.300 tỷ đồng tiền sử dụng đất dự án Lakeview City</value>
      <webElementGuid>cb65ce20-8b3f-4c0a-a384-95461ecd465c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Novaland được hoàn nhập hơn 3.300 tỷ đồng tiền sử dụng đất dự án Lakeview City</value>
      <webElementGuid>cb65ce20-8b3f-4c0a-a384-95461ecd465c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
