<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_follow</name>
   <tag></tag>
   <elementGuidId>122ced58-a8c1-4fe6-bffe-005633a6cb8e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[2]/div[1]/button[2]/*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@role,'img')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="ud-btn\ ud-btn-medium\ ud-btn-white-solid\ ud-btn-round\ ud-btn-text-sm\ ud-btn-icon\ ud-btn-icon-medium\ ud-btn-icon-round\ ud-carousel-pager-button\ ud-carousel-pager-button-next\ enriched-skills_slide-indicator-pager__QuFAy\ carousel_button__mtsms\ carousel_next-button__6VcuP"] &gt; [role="img"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=\"lohp-body\"] button &gt;&gt; nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ud-icon ud-icon-large ud-icon-bi-directional</value>
      <webElementGuid>9a7cfd64-1b05-49fa-adb1-96886916f8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9a7cfd64-1b05-49fa-adb1-96886916f8d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
