<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_trendingSkills</name>
   <tag></tag>
   <elementGuidId>29cfbba3-0a0c-4bd7-8821-982dfd86e44f</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/section[8]/div[1]/div[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="trending-skills_header-with-divider___2fXT"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=\"lohp-body\"] div &gt;&gt; nth=233</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trending-skills_header-with-divider___2fXT</value>
      <webElementGuid>9a7cfd64-1b05-49fa-adb1-96886916f8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kỹ năng phổ biến</value>
      <webElementGuid>9a7cfd64-1b05-49fa-adb1-96886916f8d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
