<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>bb3a7d8b-be18-442f-bcfe-0014a07238f7</elementGuidId>
    <imagePath></imagePath>
    <name>header_desktop</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="ud-header\ ud-text-sm\ desktop-header_header__f_kaY\ desktop-header_flex-middle__JjTaI"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/header[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"desktop-header\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ud-header ud-text-sm desktop-header_header__f_kaY desktop-header_flex-middle__JjTaI</value>
        <webElementGuid>ac3efb9d-8f6d-48a6-b673-df8641f8e2f8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>desktop-header</value>
        <webElementGuid>ac3efb9d-8f6d-48a6-b673-df8641f8e2f8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Skip to content
        Explore
        Search for anything
        Udemy Business
        Teach on Udemy
        ...[truncated lines=8]</value>
        <webElementGuid>ac3efb9d-8f6d-48a6-b673-df8641f8e2f8</webElementGuid>
    </webElementProperties>
</WebElementEntity>