<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>eafe1bf0-3c7d-4148-9571-a117957286bd</elementGuidId>
    <imagePath></imagePath>
    <name>image_rolePlayInterface</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="personal-plan-banner_image-section__qqttw"] &gt; img</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[1]/div[2]/img[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"lohp-body\"] img[alt=\"Role play interface showing AI conversation practice\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>