<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_object</name>
   <tag></tag>
   <elementGuidId>21da2194-b973-452f-b5ad-29acf8778f7b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/section[8]/div[1]/div[1]/div[1]/div[2]/div[3]/div[3]/a[1]/*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) &gt; div:nth-of-type(3) [class="ud-icon\ ud-icon-small\ ud-icon-bi-directional"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=\"lohp-body\"] a &gt;&gt; nth=37</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ud-icon ud-icon-small ud-icon-bi-directional</value>
      <webElementGuid>9a7cfd64-1b05-49fa-adb1-96886916f8d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
