<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_dataScienceTopic</name>
   <tag></tag>
   <elementGuidId>d5f13eb3-ee79-47a1-87b8-c24d6f7d40bc</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/section[8]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) &gt; div:nth-of-type(3) &gt; [class="ud-btn\ ud-btn-large\ ud-btn-link\ ud-btn-text-md\ trending-topics_title__ldN__"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=\"lohp-body\"] a &gt;&gt; internal:has-text=/^Khoa h\u1ecdc d\u1eef li\u1ec7u$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ud-btn ud-btn-large ud-btn-link ud-btn-text-md trending-topics_title__ldN__</value>
      <webElementGuid>9a7cfd64-1b05-49fa-adb1-96886916f8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/topic/data-science/</value>
      <webElementGuid>9a7cfd64-1b05-49fa-adb1-96886916f8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Khoa học dữ liệu</value>
      <webElementGuid>9a7cfd64-1b05-49fa-adb1-96886916f8d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
