<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>section_enrichedSkills2</name>
   <tag></tag>
   <elementGuidId>e44cd952-61a9-4035-96ce-ffc371cbf262</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/section[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="ud-full-viewport-container\ enriched-skills_enriched-skills-wrapper__P4gzh"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=\"lohp-body\"] section &gt;&gt; nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ud-full-viewport-container enriched-skills_enriched-skills-wrapper__P4gzh</value>
      <webElementGuid>9a7cfd64-1b05-49fa-adb1-96886916f8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Học các kỹ năng thiết yếu cho sự nghiệp và cuộc sống
      
      Udemy giúp bạn nhanh chóng xây dựng những kỹ năng đang được săn đón và thăng tiến trong một thị trường lao động không ngừng thay đổi.
      
      AI tạo sinh
      ...[truncated lines=13]</value>
      <webElementGuid>9a7cfd64-1b05-49fa-adb1-96886916f8d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
