<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_largeLanguageModels</name>
   <tag></tag>
   <elementGuidId>9a75e547-cce2-45c8-9fa0-74fcaecaae98</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/header[1]/nav[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/ul[1]/li[2]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header-browse-nav-level-three li:nth-of-type(2) &gt; [class="ud-btn\ ud-btn-medium\ ud-btn-ghost\ ud-text-sm\ list-menu_item__r7HKN\ ud-block-list-item\ ud-block-list-item-small\ ud-block-list-item-neutral"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid="browse-nav"] a &gt;&gt; internal:has-text=/^Large Language Models \(LLM\)$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ud-btn ud-btn-medium ud-btn-ghost ud-text-sm list-menu_item__r7HKN ud-block-list-item ud-block-list-item-small ud-block-list-item-neutral</value>
      <webElementGuid>60bcbc43-82b4-4c3b-ae46-7a59c59aa371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>browse-nav-item</value>
      <webElementGuid>60bcbc43-82b4-4c3b-ae46-7a59c59aa371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>{{url}}</value>
      <webElementGuid>60bcbc43-82b4-4c3b-ae46-7a59c59aa371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Large Language Models (LLM)</value>
      <webElementGuid>60bcbc43-82b4-4c3b-ae46-7a59c59aa371</webElementGuid>
   </webElementProperties>
</WebElementEntity>
