<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c829ed88-f8f9-4dc2-8550-10336cbae298</elementGuidId>
    <imagePath></imagePath>
    <name>button_generativeAiforBeginners</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(1) &gt; div &gt; [class="ud-text-sm\ filter-toggle-chip-module--button--QoVC5\ filter-toggle-chip-module--medium--tk5HH\ narrowing-suggestions--chip--ZokE2"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/main[1]/div[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:has-text=/^Generative AI for Beginners$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ud-text-sm filter-toggle-chip-module--button--{{secret_key}} filter-toggle-chip-module--medium--{{secret_key}} narrowing-suggestions--chip--ZokE2</value>
        <webElementGuid>ac3efb9d-8f6d-48a6-b673-df8641f8e2f8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Generative AI for Beginners</value>
        <webElementGuid>ac3efb9d-8f6d-48a6-b673-df8641f8e2f8</webElementGuid>
    </webElementProperties>
</WebElementEntity>