<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_basic</name>
   <tag></tag>
   <elementGuidId>5161e49b-cc0b-40a8-840f-28ecd1c5540d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="space-y-8\ md\:space-y-12\ px-4"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.space-y-8</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>space-y-8 md:space-y-12 px-4</value>
      <webElementGuid>9241bc9b-4870-4d6c-9fa9-06adeaaae745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Basic
      About
      
      Learn more about Test Automation platform
      
      ...[truncated lines=87]</value>
      <webElementGuid>9241bc9b-4870-4d6c-9fa9-06adeaaae745</webElementGuid>
   </webElementProperties>
</WebElementEntity>
