<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>header_advanced</name>
   <tag></tag>
   <elementGuidId>33110bae-0896-44dc-9159-f68abe06711d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/div[2]/div[4]/h2[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(4) &gt; .font-bold</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>h2 &gt;&gt; nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xl md:text-2xl font-bold text-gray-900 dark:text-white mb-4 md:mb-6</value>
      <webElementGuid>9241bc9b-4870-4d6c-9fa9-06adeaaae745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Advanced</value>
      <webElementGuid>9241bc9b-4870-4d6c-9fa9-06adeaaae745</webElementGuid>
   </webElementProperties>
</WebElementEntity>
