<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>list_nativeHtmlElements</name>
   <tag></tag>
   <elementGuidId>705117e0-fc59-4820-88b1-6aafd618f90e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/nav[1]/div[1]/ul[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(1) &gt; [class="space-y-1"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>ul &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>space-y-1</value>
      <webElementGuid>9241bc9b-4870-4d6c-9fa9-06adeaaae745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Native HTML Elements
      About
      Forms
      MSU Simulation Form
      Sauce Login
      ...[truncated lines=11]</value>
      <webElementGuid>9241bc9b-4870-4d6c-9fa9-06adeaaae745</webElementGuid>
   </webElementProperties>
</WebElementEntity>
