<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2769fd80-a77e-4288-9daa-1053300ec03a</elementGuidId>
    <imagePath></imagePath>
    <name>link_accessoriesFooter</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/footer[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/a[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>footer a &gt;&gt; internal:has-text=/^Accessories$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>page-footer-menu__element is-link</value>
        <webElementGuid>67a05b3f-3b64-419a-9cd4-d00984dcf2cf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/category/accessories</value>
        <webElementGuid>67a05b3f-3b64-419a-9cd4-d00984dcf2cf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Accessories</value>
        <webElementGuid>67a05b3f-3b64-419a-9cd4-d00984dcf2cf</webElementGuid>
    </webElementProperties>
</WebElementEntity>