<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>header_interestRate</name>
   <tag></tag>
   <elementGuidId>4a2593de-93bd-4f76-9d67-2e990da8aec4</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[6]/div[1]/div[1]/div[1]/article[1]/h2[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.article-topstory &gt; .title-news</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.title-news &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title-news</value>
      <webElementGuid>729c1c9c-bc4b-4a6d-9590-7fe0836b023f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Châu Âu sẵn sàng tăng lãi suất để ghìm lạm phát do chiến sự</value>
      <webElementGuid>729c1c9c-bc4b-4a6d-9590-7fe0836b023f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
