<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>80588968-650e-470c-9905-58976e1701ca</elementGuidId>
    <imagePath></imagePath>
    <name>link_dynamicObject</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[5]/div[1]/div[1]/div[1]/article[1]/h3[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Đồ hộp Hạ Lo{{name}}ả lương công nhân khi dừng sản xuất')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"${link_dynamicObject_AInternalText_1}\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}-cong-nhan-khi-dung-san-xuat-5005098.{{url}}</value>
        <webElementGuid>b1fca37d-a0df-41fa-9639-39240fef6512</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Đồ hộp Hạ Lo{{name}}ả lương công nhân khi dừng sản xuất</value>
        <webElementGuid>b1fca37d-a0df-41fa-9639-39240fef6512</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Đồ hộp Hạ Lo{{name}}ả lương công nhân khi dừng sản xuất</value>
        <webElementGuid>b1fca37d-a0df-41fa-9639-39240fef6512</webElementGuid>
    </webElementProperties>
</WebElementEntity>