<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_iframes</name>
   <tag></tag>
   <elementGuidId>4cbc6602-5e9b-4469-b3e7-334bf059ae9a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/nav[1]/div[3]/ul[1]/li[4]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@href,'/iframes') and equals(@text,'Iframes')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="flex\ items-center\ px-3\ py-2\ text-sm\ rounded-md\ bg-blue-50\ dark\:bg-blue-900\/50\ text-blue-600\ dark\:text-blue-400"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a &gt;&gt; internal:text="Iframes"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center px-3 py-2 text-sm rounded-md bg-blue-50 dark:bg-blue-900/50 text-blue-600 dark:text-blue-400</value>
      <webElementGuid>642d05a1-8ce6-48f7-9cc9-bc0470e38d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/iframes</value>
      <webElementGuid>642d05a1-8ce6-48f7-9cc9-bc0470e38d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iframes</value>
      <webElementGuid>642d05a1-8ce6-48f7-9cc9-bc0470e38d4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
