<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>header_howToUseThisPage</name>
   <tag></tag>
   <elementGuidId>05ea2009-d3a4-4772-b319-de325b8c300d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[1]/h2[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;mx-auto\ max-w-7xl\ space-y-8\ p-6&quot;] > .border > .font-semibold</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'How to use this page' or . = 'How to use this page')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>h2 >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-3 text-lg font-semibold text-gray-900 dark:text-white</value>
      <webElementGuid>822a0c58-f972-4700-8c2e-cd5469c26303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How to use this page</value>
      <webElementGuid>822a0c58-f972-4700-8c2e-cd5469c26303</webElementGuid>
   </webElementProperties>
</WebElementEntity>
