<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_xpathBreakingCharacters</name>
   <tag></tag>
   <elementGuidId>0267190d-eaba-4162-9cef-081d49d8c4b9</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[2]/nav[1]/div[3]/ul[1]/li[12]/a[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) li:nth-of-type(12) > .flex</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/xpath-breaking' and (text() = 'XPath Breaking Characters' or . = 'XPath Breaking Characters')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;nav-xpath-breaking&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center px-3 py-2 text-sm rounded-md text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700</value>
      <webElementGuid>5f6633c2-0476-47f7-b3a8-f7af77a8d63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/xpath-breaking</value>
      <webElementGuid>5f6633c2-0476-47f7-b3a8-f7af77a8d63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>XPath Breaking Characters</value>
      <webElementGuid>5f6633c2-0476-47f7-b3a8-f7af77a8d63d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
