<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_searchSuggestion</name>
   <tag></tag>
   <elementGuidId>42eb0f0e-a54a-4b24-a14f-4ccfd157b130</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/header[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="sc-66af1b06-0\ hilSzk"] &gt; a:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a &gt;&gt; internal:has-text=/^th\u1ebb c\u00e0o viettel$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item  </value>
      <webElementGuid>149c0d05-27f8-40ae-b449-8ef421fa41dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search?q=th%E1%BA%BB%20c%C3%A0o%20viettel</value>
      <webElementGuid>149c0d05-27f8-40ae-b449-8ef421fa41dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>thẻ cào viettel</value>
      <webElementGuid>149c0d05-27f8-40ae-b449-8ef421fa41dd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
