<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_accountManagement</name>
   <tag></tag>
   <elementGuidId>90c6e4a9-1425-42f1-9654-5ec282917be6</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/aside[1]/div[1]/div[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@href,'#account-crm') and equals(@text,'Relationship Management / Customer Relationship Management / Account
         Account - CRM')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifs-account-crm-link</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ifs-account-crm-link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#account-crm</value>
      <webElementGuid>3361055c-cae9-4b3b-8475-965e83131a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifs-account-crm-link</value>
      <webElementGuid>3361055c-cae9-4b3b-8475-965e83131a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Relationship Management / Customer Relationship Management / Account
      Account - CRM</value>
      <webElementGuid>3361055c-cae9-4b3b-8475-965e83131a9f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
