<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>main_pageSourceRepro</name>
   <tag></tag>
   <elementGuidId>4ddba582-c27a-41f2-bfcf-d73f55972f70</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/main[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'PAGE SOURCE REPRO
         IFS-like nested text reproduction
         
         This standalone HTML mirrors the structure from 1 - Page Source.txt more closely than the earlier React POC.
         
         ...[truncated lines=13]')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.main</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>main</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>3361055c-cae9-4b3b-8475-965e83131a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAGE SOURCE REPRO
      IFS-like nested text reproduction
      
      This standalone HTML mirrors the structure from 1 - Page Source.txt more closely than the earlier React POC.
      
      ...[truncated lines=13]</value>
      <webElementGuid>3361055c-cae9-4b3b-8475-965e83131a9f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
