<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_thoughtLeadership</name>
   <tag></tag>
   <elementGuidId>36eb4dfd-e3a8-48df-9d88-7a3ed129060e</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/div[1]/div[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="et_pb_section\ et_pb_section_8\ et_pb_with_background\ et_section_regular"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(9)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_section et_pb_section_8 et_pb_with_background et_section_regular</value>
      <webElementGuid>6dc6b2e3-7cf9-4ac1-8ab9-47303032c3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thought leadership
      
      Stay ahead with our weekly blog updates. Follow Ultimate QA for the latest test automation guides, reviews, and insights.
      
      Read More
      ...[truncated lines=46]</value>
      <webElementGuid>6dc6b2e3-7cf9-4ac1-8ab9-47303032c3cb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
