<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_newGoldStandardQa</name>
   <tag></tag>
   <elementGuidId>8c9214e6-50e1-4451-95aa-f21b3d992c91</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/div[1]/div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="et_pb_section\ et_pb_section_4\ et_pb_with_background\ et_section_regular"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.et_builder_inner_content &gt; div:nth-child(5)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>{{unknown}}</value>
      <webElementGuid>923b3efd-a899-4f0f-a788-4f4838c98427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Introducing A New Gold Standard In QA Testing And Product Performance
      
      Only one-quarter of all automated tests pass 90% or more on desktop and mobile. Most automation is actually a huge cost of time and money to the business.</value>
      <webElementGuid>923b3efd-a899-4f0f-a788-4f4838c98427</webElementGuid>
   </webElementProperties>
</WebElementEntity>
