<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_pushHigherQualitySoftware</name>
   <tag></tag>
   <elementGuidId>a13a0335-1064-48e3-94a5-134c8cdc5e51</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="et_pb_column\ et_pb_column_1_2\ et_pb_column_0\ \ et_pb_css_mix_blend_mode_passthrough"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div &gt; .et_builder_inner_content &gt; div &gt; div &gt; div &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>{{unknown}}</value>
      <webElementGuid>923b3efd-a899-4f0f-a788-4f4838c98427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Push Higher Quality Software To Market Faster
      
      UltimateQA’s customized, efficient QA test automation solutions help software teams become more efficient and companies more profitable.
      
      FREE STRATEGY SESSION</value>
      <webElementGuid>923b3efd-a899-4f0f-a788-4f4838c98427</webElementGuid>
   </webElementProperties>
</WebElementEntity>
