<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_seeFullStory</name>
   <tag></tag>
   <elementGuidId>7c0dad5d-e810-415a-9783-95605c83589c</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/div[1]/div[7]/div[2]/div[2]/div[3]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="et_pb_button\ et_pb_button_3\ show-full-story\ et_pb_bg_layout_light"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a &gt;&gt; internal:text="See Full Story"s &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_button et_pb_button_3 show-full-story et_pb_bg_layout_light</value>
      <webElementGuid>923b3efd-a899-4f0f-a788-4f4838c98427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>{{url}}</value>
      <webElementGuid>923b3efd-a899-4f0f-a788-4f4838c98427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>See Full Story</value>
      <webElementGuid>923b3efd-a899-4f0f-a788-4f4838c98427</webElementGuid>
   </webElementProperties>
</WebElementEntity>
