<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8dc09c53-a5b5-4ade-9427-8e87779a968e</elementGuidId>
    <imagePath></imagePath>
    <name>body_darkTheme</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="dark_theme"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#dark_theme</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>dark_theme</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>{{address}}
        Mặc định
        29 o
        Thứ hai, {{date_time}}
        Mới nhất
        ...[truncated lines=537]</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
</WebElementEntity>