<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_health</name>
   <tag></tag>
   <elementGuidId>a17eac96-9cce-4258-a69c-587f09b2a457</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[1]/nav[1]/ul[1]/li[11]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Sức khỏe')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="suckhoe\ "] &gt; a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>nav a[title="Sức khỏe"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>{{url}}</value>
      <webElementGuid>cb65ce20-8b3f-4c0a-a384-95461ecd465c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sức khỏe</value>
      <webElementGuid>cb65ce20-8b3f-4c0a-a384-95461ecd465c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sức khỏe</value>
      <webElementGuid>cb65ce20-8b3f-4c0a-a384-95461ecd465c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
