<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6926f2bd-ae3d-4fd3-8d58-8447fc0e87df</elementGuidId>
    <imagePath></imagePath>
    <name>link_itemSucKhoe</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="suckhoe\ "] &gt; a</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/section[2]/nav[1]/ul[1]/li[11]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Sức khỏe')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>nav a[title=\"S\u1ee9c kh\u1ecfe\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sức khỏe</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Sức khỏe</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
</WebElementEntity>