<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a2431e19-2f31-46b7-b205-182a0279285e</elementGuidId>
    <imagePath></imagePath>
    <name>link_itemDanQuan</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>body:nth-of-type(1) &gt; section:nth-of-type(13) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; article:nth-of-type(1) &gt; div:nth-of-type(2) &gt; h3:nth-of-type(1) &gt; a:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/section[13]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/article[1]/div[2]/h3[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Dân quân {{address}} hoan nghênh tân Lãnh tụ Tối cao {{address}}')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text=/^D\u00e2n qu\u00e2n {{address}} hoan ngh\u00eanh t\u00e2n L\u00e3nh t\u1ee5 T\u1ed1i cao {{address}}/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Dân quân {{address}} hoan nghênh tân Lãnh tụ Tối cao {{address}}</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Dân quân {{address}} hoan nghênh tân Lãnh tụ Tối cao {{address}}</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
</WebElementEntity>