<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>278fdd47-209c-486d-a62e-9f67082074f1</elementGuidId>
    <imagePath></imagePath>
    <name>link_scrollToTop2</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="to_top"] &gt; [class="ic\ ic-arrow-up"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/a[1]/*[name()='svg'][1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a[title=\"L\u00ean \u0111\u1ea7u trang\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ic ic-arrow-up</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
</WebElementEntity>