<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_trangChu</name>
   <tag></tag>
   <elementGuidId>8a902c4a-2369-4cbf-8b82-c61e547cc213</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[1]/nav[1]/ul[1]/li[1]/a[1]/*[name()='svg'][2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.flexbox > [class=&quot;ic\ ic-evne&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#wrap-main-nav a[title=&quot;Trang chủ&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>{{password}}</value>
      <webElementGuid>df8b8130-6c22-4107-a437-4a9833fe091a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
