<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>p_newsDate</name>
   <tag></tag>
   <elementGuidId>70f6c1c7-047a-4fce-9a73-c272ba28678d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[5]/div[1]/div[2]/article[1]/p[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;fck_detail\ &quot;] > p:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Ngày {{date_time}}, Quốc hội phê chuẩn bổ nhiệm PGS. TS {{name}} làm Bộ trưởng Giáo dục và Đào tạo. Đây luôn là "ghế nóng" với bộ máy nhân sự khổng lồ - hơn 1,6 triệu thầy cô, tác động đến khoảng 26 triệu học sinh, sinh viên.' or . = 'Ngày {{date_time}}, Quốc hội phê chuẩn bổ nhiệm PGS. TS {{name}} làm Bộ trưởng Giáo dục và Đào tạo. Đây luôn là "ghế nóng" với bộ máy nhân sự khổng lồ - hơn 1,6 triệu thầy cô, tác động đến khoảng 26 triệu học sinh, sinh viên.')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>p >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Normal</value>
      <webElementGuid>df8b8130-6c22-4107-a437-4a9833fe091a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ngày {{date_time}}, Quốc hội phê chuẩn bổ nhiệm PGS. TS {{name}} làm Bộ trưởng Giáo dục và Đào tạo. Đây luôn là "ghế nóng" với bộ máy nhân sự khổng lồ - hơn 1,6 triệu thầy cô, tác động đến khoảng 26 triệu học sinh, sinh viên.</value>
      <webElementGuid>df8b8130-6c22-4107-a437-4a9833fe091a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
