<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_manualTesting</name>
   <tag></tag>
   <elementGuidId>b33546af-ea38-4305-80db-f2c92c5ef3fa</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/header[1]/section[2]/div[1]/div[1]/nav[1]/ul[1]/li[1]/div[2]/div[1]/div[2]/div[2]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.main-wrapper &gt; div:nth-of-type(2) &gt; [class="product_list"] &gt; a:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) &gt; .product_list &gt; a &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product_item</value>
      <webElementGuid>c4e023ce-28ac-40ad-be15-103e549303a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/testops#manual-testing</value>
      <webElementGuid>c4e023ce-28ac-40ad-be15-103e549303a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manual Testing </value>
      <webElementGuid>c4e023ce-28ac-40ad-be15-103e549303a6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
