<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_consultingRow</name>
   <tag></tag>
   <elementGuidId>bc1657c1-7b76-43cb-9ed2-20b1bce26e8a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/div[1]/div[3]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.flex</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.et_builder_inner_content &gt; div:nth-child(3) &gt; div &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_row et_pb_row_3 flex flex-align-center</value>
      <webElementGuid>923b3efd-a899-4f0f-a788-4f4838c98427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>{{unknown}}</value>
      <webElementGuid>923b3efd-a899-4f0f-a788-4f4838c98427</webElementGuid>
   </webElementProperties>
</WebElementEntity>
