<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_consultingContent</name>
   <tag></tag>
   <elementGuidId>8f4c3dd3-08fa-49ec-bbbd-355f5d18d257</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[4]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="et_pb_with_border\ et_pb_module\ et_pb_blurb\ et_pb_blurb_3\ \ et_pb_text_align_center\ \ et_pb_blurb_position_top\ et_pb_bg_layout_light"] &gt; [class="et_pb_blurb_content"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(4) &gt; .et_pb_with_border &gt; .et_pb_blurb_content</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_blurb_content</value>
      <webElementGuid>6dc6b2e3-7cf9-4ac1-8ab9-47303032c3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>{{unknown}}</value>
      <webElementGuid>6dc6b2e3-7cf9-4ac1-8ab9-47303032c3cb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
