<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_bestTestAutomationSolutions</name>
   <tag></tag>
   <elementGuidId>adad17e1-3347-4b05-86e1-325afe0f90f5</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="et_pb_section\ et_pb_section_0\ et_section_regular"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div &gt; .et_builder_inner_content &gt; div &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>{{unknown}}</value>
      <webElementGuid>6dc6b2e3-7cf9-4ac1-8ab9-47303032c3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>World's Best Test Automation Solutions
      
      Poor software quality can be the exception rather than the norm. UltimateQA’s automated QA testing saves time and money and protects a company’s reputation for the fast, flawless delivery of IT that actually works.
      
      SCHEDULE A FREE DISCOVERY SESSION</value>
      <webElementGuid>6dc6b2e3-7cf9-4ac1-8ab9-47303032c3cb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
