<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_threeZodiac</name>
   <tag></tag>
   <elementGuidId>9c4ccb9f-bcb4-455a-a190-fea13b07cc35</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[6]/div[1]/div[1]/div[1]/article[1]/h3[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'3 con giáp càng chăm chỉ càng nhiều tài lộc trong năm nay')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.full-thumb &gt; .title-news &gt; a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a &gt;&gt; internal:text="3 con giáp càng chăm chỉ càng nhiều tài lộc trong năm nay"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>{{url}}</value>
      <webElementGuid>cb65ce20-8b3f-4c0a-a384-95461ecd465c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3 con giáp càng chăm chỉ càng nhiều tài lộc trong năm nay</value>
      <webElementGuid>cb65ce20-8b3f-4c0a-a384-95461ecd465c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3 con giáp càng chăm chỉ càng nhiều tài lộc trong năm nay</value>
      <webElementGuid>cb65ce20-8b3f-4c0a-a384-95461ecd465c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
