<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f1a0562c-05a6-4ab6-9aac-dc042dacd1f8</elementGuidId>
    <imagePath></imagePath>
    <name>div_fullViewport</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>section:nth-of-type(1) &gt; [class="ud-full-viewport-container"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/section[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.ud-full-viewport-container &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ud-full-viewport-container</value>
        <webElementGuid>adda66f6-a5bb-4aad-8c46-9532c24e5210</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Các khóa học có giá từ 309.000 ₫
        
        Định hình cơ hội nghề nghiệp của bạn với kỹ năng lãnh đạo và AI. Ưu đãi kết thúc vào ngày {{date_time}}
        
        Tiết kiệm ngay
        ...[truncated lines=22]</value>
        <webElementGuid>adda66f6-a5bb-4aad-8c46-9532c24e5210</webElementGuid>
    </webElementProperties>
</WebElementEntity>