<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_browseAwsarchitectAssociate</name>
   <tag></tag>
   <elementGuidId>9103aebf-8b5a-4505-b25c-90263073cc29</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/header[1]/nav[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/ul[1]/li[1]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul:nth-child(1) &gt; li:nth-of-type(1) &gt; [class="ud-btn\ ud-btn-medium\ ud-btn-ghost\ ud-text-sm\ list-menu_item__r7HKN\ ud-block-list-item\ ud-block-list-item-small\ ud-block-list-item-neutral"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid="browse-nav"] a &gt;&gt; internal:has-text=/^AWS Certified Solutions Architect - Associate$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ud-btn ud-btn-medium ud-btn-ghost ud-text-sm list-menu_item__r7HKN ud-block-list-item ud-block-list-item-small ud-block-list-item-neutral</value>
      <webElementGuid>e1f0ae28-103a-495a-ab4f-10c1827c8638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>browse-nav-item</value>
      <webElementGuid>e1f0ae28-103a-495a-ab4f-10c1827c8638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/topic/aws-certified-solutions-architect-associate/</value>
      <webElementGuid>e1f0ae28-103a-495a-ab4f-10c1827c8638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AWS Certified Solutions Architect - Associate</value>
      <webElementGuid>e1f0ae28-103a-495a-ab4f-10c1827c8638</webElementGuid>
   </webElementProperties>
</WebElementEntity>
