<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_caseStudies</name>
   <tag></tag>
   <elementGuidId>ad3da805-3f0b-41ec-8b11-16d1d905666b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="et_pb_column\ et_pb_column_4_4\ et_pb_column_0\ \ et_pb_css_mix_blend_mode_passthrough\ et-last-child"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div &gt; .et_builder_inner_content &gt; div &gt; .et_pb_row &gt; .et_pb_column &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_column et_pb_column_4_4 et_pb_column_0  et_pb_css_mix_blend_mode_passthrough et-last-child</value>
      <webElementGuid>6dc6b2e3-7cf9-4ac1-8ab9-47303032c3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>{{unknown}}</value>
      <webElementGuid>6dc6b2e3-7cf9-4ac1-8ab9-47303032c3cb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
