<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>footer_home</name>
   <tag></tag>
   <elementGuidId>a64f232c-a459-4aa0-a21d-ac1fccc5e4be</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[3]/footer[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.footer</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>footer</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer</value>
      <webElementGuid>c4e023ce-28ac-40ad-be15-103e549303a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Platform
      
      Test Automation
      with Katalon Studio
      Test Management
      ...[truncated lines=57]</value>
      <webElementGuid>c4e023ce-28ac-40ad-be15-103e549303a6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
