<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>20fc484c-c775-4244-b7cb-b2b0cbf1528c</elementGuidId>
    <imagePath></imagePath>
    <name>link_showAll</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[2]/nav[1]/ul[1]/li[21]/a[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"T\u1ea5t c\u1ea3\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>javascript:;</value>
        <webElementGuid>1667b12a-4cde-4f09-9732-f8b17360b93a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Tất cả</value>
        <webElementGuid>1667b12a-4cde-4f09-9732-f8b17360b93a</webElementGuid>
    </webElementProperties>
</WebElementEntity>