<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>609a247c-9f30-48de-8930-793531fda26a</elementGuidId>
    <imagePath></imagePath>
    <name>link_kCellphoneShopLogo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/header[1]/section[1]/div[1]/div[1]/a[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text=/^K Cellphone Shop$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>mars-logo-row__logo</value>
        <webElementGuid>67a05b3f-3b64-419a-9cd4-d00984dcf2cf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/</value>
        <webElementGuid>67a05b3f-3b64-419a-9cd4-d00984dcf2cf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>K Cellphone Shop</value>
        <webElementGuid>67a05b3f-3b64-419a-9cd4-d00984dcf2cf</webElementGuid>
    </webElementProperties>
</WebElementEntity>