<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_katalonStudio</name>
   <tag></tag>
   <elementGuidId>adfe7e93-4194-4c5e-974c-1e11aeda65fb</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/header[1]/section[2]/div[1]/div[1]/nav[1]/ul[1]/li[1]/div[2]/div[1]/div[1]/div[2]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.main-wrapper &gt; div:nth-of-type(1) [class="product_item"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.product_item &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product_item</value>
      <webElementGuid>c4e023ce-28ac-40ad-be15-103e549303a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/katalon-studio</value>
      <webElementGuid>c4e023ce-28ac-40ad-be15-103e549303a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Studio </value>
      <webElementGuid>c4e023ce-28ac-40ad-be15-103e549303a6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
