<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_bachHoaOnline</name>
   <tag></tag>
   <elementGuidId>e2e5961d-7ac4-4a93-9c08-038f077cdb3a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/main[1]/div[1]/div[1]/div[1]/div[1]/div[11]/div[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Bách Hóa Online')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(11) &gt; .hagwli &gt; a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a[title=\"B\u00e1ch H\u00f3a Online\"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/bach-hoa-online/c4384</value>
      <webElementGuid>149c0d05-27f8-40ae-b449-8ef421fa41dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bách Hóa Online</value>
      <webElementGuid>149c0d05-27f8-40ae-b449-8ef421fa41dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bách Hóa Online</value>
      <webElementGuid>149c0d05-27f8-40ae-b449-8ef421fa41dd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
