<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_testStrategyConsultation</name>
   <tag></tag>
   <elementGuidId>b4c02683-369a-44cd-9509-2545f604d75b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="et_pb_with_border\ et_pb_module\ et_pb_blurb\ et_pb_blurb_2\ \ et_pb_text_align_center\ \ et_pb_blurb_position_top\ et_pb_bg_layout_light"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(3) &gt; .et_pb_with_border &gt;&gt; nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et_pb_with_border et_pb_module et_pb_blurb et_pb_blurb_2  et_pb_text_align_center  et_pb_blurb_position_top et_pb_bg_layout_light</value>
      <webElementGuid>ce1f0dd8-bbee-4f26-b90f-7447e68c7389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Strategy Consultation
      
      Crafting a successful testing strategy is a cornerstone of software development. Our Test Strategy Consultation services provide you with a roadmap to navigate the complexities of testing. From comprehensive test planning to risk assessment, our experts collaborate with your team to define a tailored testing strategy that aligns with your project goals.</value>
      <webElementGuid>ce1f0dd8-bbee-4f26-b90f-7447e68c7389</webElementGuid>
   </webElementProperties>
</WebElementEntity>
