<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>image_testing</name>
   <tag></tag>
   <elementGuidId>345849ff-89e9-460a-bb63-8b53e4a95c6d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/div[1]/div[1]/article[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[4]/div[1]/div[1]/div[1]/span[1]/img[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="et-waypoint\ et_pb_animation_top\ et_pb_animation_top_tablet\ et_pb_animation_top_phone\ wp-image-218053\ lazyloaded"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>img[alt=\"testing\"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>et-waypoint et_pb_animation_top et_pb_animation_top_tablet et_pb_animation_top_phone wp-image-218053 lazyloaded</value>
      <webElementGuid>ce1f0dd8-bbee-4f26-b90f-7447e68c7389</webElementGuid>
   </webElementProperties>
</WebElementEntity>
