<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>main_content</name>
   <tag></tag>
   <elementGuidId>78e3c413-4da1-4fbe-a58c-b0afc86d5f97</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main-content-anchor</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#main-content-anchor</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>layout_content__wSshz</value>
      <webElementGuid>e1f0ae28-103a-495a-ab4f-10c1827c8638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main-content-anchor</value>
      <webElementGuid>e1f0ae28-103a-495a-ab4f-10c1827c8638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DP-203: Microsoft Azure Data Engineer Associate (Retired) Courses
      DP-203: Microsoft Azure Data Engineer Associate (Retired) relates to
      IT &amp; Software
      IT Certifications
      Looking to advance your skills in DP-203: Microsoft Azure Data Engineer Associate (Retired)? We've got you.
      ...[truncated lines=332]</value>
      <webElementGuid>e1f0ae28-103a-495a-ab4f-10c1827c8638</webElementGuid>
   </webElementProperties>
</WebElementEntity>
