<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>appQuestionFormItem_timeDisplay</name>
   <tag></tag>
   <elementGuidId>fdc60645-bf32-4128-8fbc-b6eb41d7ac99</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-claim-questions[1]/app-questionnaire[1]/app-question-form-list[1]/app-question-form-item[1]/app-question-form-item[1]/app-question-form-item[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#time</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' {{date_time}} ' or . = ' {{date_time}} ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:testid=[class=&quot;grid-xxl-6 grid-xl-6 grid-lg-7 grid-md-7 grid-sm-12 empty-parent ng-star-inserted&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid-xxl-6 grid-xl-6 grid-lg-7 grid-md-7 grid-sm-12 empty-parent ng-star-inserted</value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> {{date_time}} </value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
