<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>span_calendarDayCell3</name>
   <tag></tag>
   <elementGuidId>0c02bec8-0154-4031-bc46-40a5dec06c9b</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[2]/div[1]/cds-datepicker-content[1]/cds-calendar[1]/div[1]/cds-calendar-month[1]/section[4]/cds-calendar-item[3]/span[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.today > [class=&quot;cds-calendar-item__content&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '14' or . = '14')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:testid=[class=&quot;cds-detail1 cds-demibold cds-calendar-item cds-calendar-cell today ng-star-inserted&quot;s] >> internal:testid=[class=&quot;cds-calendar-item__content&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cds-calendar-item__content</value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
