<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>span_periodOfHospitalizationDateRangeLabel</name>
   <tag></tag>
   <elementGuidId>d8ab689a-457f-4752-ae83-d0ee8f6158f7</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-hospitalization-benetifs[1]/div[1]/div[2]/span[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.flex > .font-normal</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Period of Hospitalization (DD/MM/YYYY) to (DD/MM/YYYY)' or . = 'Period of Hospitalization (DD/MM/YYYY) to (DD/MM/YYYY)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:testid=[class=&quot;flex flex-col mt-10 ng-star-inserted&quot;s] >> internal:testid=[class=&quot;font-normal&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_ngcontent-ng-c2064770431</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-normal</value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Period of Hospitalization (DD/MM/YYYY) to (DD/MM/YYYY)</value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
