<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>label_ratings</name>
   <tag></tag>
   <elementGuidId>a76ea909-e2ca-4842-8ffe-3642e55075e2</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]/div[2]/div[9]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[for="radio--351"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label &gt;&gt; internal:text="4.5 out of 5 &amp; up4.5 &amp; up(52)Results"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ud-toggle-input-container ud-text-sm</value>
      <webElementGuid>60bcbc43-82b4-4c3b-ae46-7a59c59aa371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4.5 out of 5 &amp; up
      4.5 &amp; up
      (52)
      Results</value>
      <webElementGuid>60bcbc43-82b4-4c3b-ae46-7a59c59aa371</webElementGuid>
   </webElementProperties>
</WebElementEntity>
