<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>079f0e1f-4f2f-4de0-94e2-5afb89dca121</elementGuidId>
    <imagePath></imagePath>
    <name>link_moiNhat</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[2]/section[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[2]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Mới nhất')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#wrap-main-nav section a[title=\"M\u1edbi nh\u1ea5t\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>1667b12a-4cde-4f09-9732-f8b17360b93a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Mới nhất</value>
        <webElementGuid>1667b12a-4cde-4f09-9732-f8b17360b93a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Mới nhất</value>
        <webElementGuid>1667b12a-4cde-4f09-9732-f8b17360b93a</webElementGuid>
    </webElementProperties>
</WebElementEntity>