<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_analysis</name>
   <tag></tag>
   <elementGuidId>a7a1a163-7e0b-41b2-aafb-19e19192a852</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[6]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="container\ flexbox"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section:nth-child(11) &gt; .container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container flexbox</value>
      <webElementGuid>cb65ce20-8b3f-4c0a-a384-95461ecd465c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lý do Mỹ - Iran bất đồng về đàm phán chấm dứt xung đột
      
      Tín hiệu đàm phán từ ông {{name}} mở ra hy vọng, song hai bên bất đồng vì thiếu niềm tin chiến lược, đòi hỏi cam kết vững chắc và bên bảo lãnh đủ uy tín để kết thúc chiến sự. 
      
      Nguy cơ Iran tạo điểm nghẽn năng lượng mới ở biển Đỏ
      ...[truncated lines=163]</value>
      <webElementGuid>cb65ce20-8b3f-4c0a-a384-95461ecd465c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
