<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_khoaHocCongNghe</name>
   <tag></tag>
   <elementGuidId>d50e27b2-a5c6-46eb-af4f-ee888b72328a</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[1]/nav[1]/ul[1]/li[7]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Khoa học công nghệ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="khoahoccongnghe\ "] &gt; a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#wrap-main-nav nav a[title="Khoa học công nghệ"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>{{url}}</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Khoa học công nghệ</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Khoa học công nghệ</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
