<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f7713a41-336e-4600-802b-23bfd9837a7a</elementGuidId>
    <imagePath></imagePath>
    <name>div_transactionInfo</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>#framework-bodyWrap</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@role,'presentation')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#framework-bodyWrap</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>x-panel-bodyWrap newUIExpanded</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>framework-bodyWrap</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>presentation</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Transaction ID: -1 Elapsed Time: 0.21s
        Carrier Home ({{address}}) - ({{phone}})
        	
        	
        	
        ...[truncated lines=284]</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
</WebElementEntity>