<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2ee2337f-dff8-430d-8076-147c01e33786</elementGuidId>
    <imagePath></imagePath>
    <name>div_customerTypeSection</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="blk_22322654399_1583848-body"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[1]/div[2]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@role,'presentation')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#{{us_individual_tax_identification_number}}</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>x-panel-body x-panel-body-default x-table-layout-ct x-panel-body-default x-noborder-t x-panel-default-outer-border-rbl</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>{{us_individual_tax_identification_number}}</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>presentation</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Customer Type*
        
        
        	
        	
        ...[truncated lines=22]</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
</WebElementEntity>