<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>93994ba9-9463-4a49-8cf4-5361eb6770d2</elementGuidId>
    <imagePath></imagePath>
    <name>div_navigationMenu</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[id="osapplayout-1090-body"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@role,'form')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#{{username}}</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>x-panel-body x-panel-body-default x-docked-left x-panel-body-docked-left x-panel-body-default-docked-left x-table-layout-ct x-panel-body-default x-panel-body-default-docked-left x-scroller x-panel-default-outer-border-trbl</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>{{username}}</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>form</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>
        
        Home
        
        
        ...[truncated lines=26]</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
</WebElementEntity>