<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cbd16341-54b8-4037-853b-cccc5861b316</elementGuidId>
    <imagePath></imagePath>
    <name>link_directBusiness</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="x-btn\ x-unselectable\ x-box-item\ x-btn-default-small\ action-level1-button\ x-btn-over\ x-btn-pressed"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[5]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[1]/div[1]/div[1]/a[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@role,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#{{username}}</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>x-btn x-unselectable x-box-item x-btn-default-small action-level1-button x-btn-over x-btn-pressed</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>role</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Direct Business</value>
        <webElementGuid>85374e57-a96b-4c30-92ef-d5aec6a2fd77</webElementGuid>
    </webElementProperties>
</WebElementEntity>