<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>14e8bc4c-7796-443f-adc5-802531bf1241</elementGuidId>
    <imagePath></imagePath>
    <name>label_toggle</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[for="checkbox--478"] &gt; [class="ud-icon\ ud-icon-xsmall\ ud-fake-toggle-input\ ud-fake-toggle-checkbox"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/main[1]/div[2]/div[9]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]/*[name()='svg'][1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.ud-toggle-input-container &gt; .ud-icon &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ud-icon ud-icon-xsmall ud-fake-toggle-input ud-fake-toggle-checkbox</value>
        <webElementGuid>ac3efb9d-8f6d-48a6-b673-df8641f8e2f8</webElementGuid>
    </webElementProperties>
</WebElementEntity>