<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>873fe91e-6686-4967-b63d-f3c2907bec3f</elementGuidId>
    <imagePath></imagePath>
    <name>link_udemyLogo</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="desktop-header_flex-middle__JjTaI\ desktop-header_logo__wQjhP"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/header[1]/a[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.ud-header &gt; .desktop-header_flex-middle__JjTaI</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>desktop-header_flex-middle__JjTaI desktop-header_logo__wQjhP</value>
        <webElementGuid>adda66f6-a5bb-4aad-8c46-9532c24e5210</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/</value>
        <webElementGuid>adda66f6-a5bb-4aad-8c46-9532c24e5210</webElementGuid>
    </webElementProperties>
</WebElementEntity>