<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>main_generativeAi</name>
   <tag></tag>
   <elementGuidId>459358bd-a9ba-4d4b-96dc-089fcd5e9ca1</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[1]/main[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#main-content-anchor</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#main-content-anchor</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>layout_content__wSshz</value>
      <webElementGuid>60bcbc43-82b4-4c3b-ae46-7a59c59aa371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main-content-anchor</value>
      <webElementGuid>60bcbc43-82b4-4c3b-ae46-7a59c59aa371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generative AI (GenAI) Courses
      Generative AI (GenAI) relates to
      IT &amp; Software
      Business
      Looking to advance your skills in Generative AI (GenAI)? We've got you.
      ...[truncated lines=582]</value>
      <webElementGuid>60bcbc43-82b4-4c3b-ae46-7a59c59aa371</webElementGuid>
   </webElementProperties>
</WebElementEntity>
