<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_container</name>
   <tag></tag>
   <elementGuidId>20e3e0d6-dcc7-47a2-b950-49b75dc86f90</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[6]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="container\ flexbox"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section:nth-child(12) &gt; .container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container flexbox</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mỹ có thể đang đàm phán thế nào với Iran
      
      Phát biểu của ông {{name}} cho thấy một tiến trình đàm phán giữa Mỹ với Iran có thể đang hình thành qua các kênh gián tiếp, nhưng chưa có dấu hiệu đột phá rõ ràng. 
      
      Lý do máy bay Canada nát mũi khi va chạm với xe cứu hỏa
      ...[truncated lines=157]</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
