<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>aside_navigatorMenu</name>
   <tag></tag>
   <elementGuidId>5cd684d2-08db-4ef1-b373-e7d116f80016</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/aside[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@text,'Navigator menu
         Relationship Management / Customer Relationship Management / Account
         Account - CRM
         Relationship Management / Customer Relationship Management / Account
         Accounts - CRM')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.sidebar</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>aside</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar</value>
      <webElementGuid>3361055c-cae9-4b3b-8475-965e83131a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Navigator menu
      Relationship Management / Customer Relationship Management / Account
      Account - CRM
      Relationship Management / Customer Relationship Management / Account
      Accounts - CRM</value>
      <webElementGuid>3361055c-cae9-4b3b-8475-965e83131a9f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
