<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a74a510e-f35d-4dbf-892d-6f933889cb2f</elementGuidId>
    <imagePath></imagePath>
    <name>section_topStories</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>${section_topStories_css_value_4}</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/section[5]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>section:nth-child(11)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>section section_topstory</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Láng giềng cảnh báo Iran sẽ phải trả giá nếu tiếp tục tập kích khắp Vùng Vịnh
        
        Nhiều quốc gia Vùng Vịnh lên án các cuộc tập kích từ Iran trên khắp khu vực, cảnh báo Tehran đã tính toán sai và có thể phải trả giá.
        
        "Chúng tôi cảm thấy bị phản bội trầm trọng. Đây đã là lần ...
        ...[truncated lines=17]</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
</WebElementEntity>