<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>span_roleOptions</name>
   <tag></tag>
   <elementGuidId>117ddefa-621c-4a79-b811-d73b1334b4ae</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/div[1]/div[1]/div[1]/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>${span_roleOptions_css_value_1}</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(${span_roleOptions_DivNthChild_1}) &gt; .mb-4 &gt; .rounded-full</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-full bg-gray-100 px-2.5 py-1 text-xs font-medium text-gray-700 dark:bg-gray-800 dark:text-gray-300</value>
      <webElementGuid>37c1589f-6609-4532-a1b3-65ebce8f4e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>role="option"</value>
      <webElementGuid>37c1589f-6609-4532-a1b3-65ebce8f4e4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
