<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_yesNoOptions</name>
   <tag></tag>
   <elementGuidId>5acc604f-3a1f-4181-8c69-15c8d088af48</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-hospitalization-benetifs[1]/div[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;flex\ flex-col\ mt-5\ tb\:flex-row&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'flex flex-col mt-5 tb:flex-row' and (text() = 'YesNo' or . = 'YesNo')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.flex-options &gt; .flex</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_ngcontent-ng-c2064770431</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2abfd0a2-d81d-4c03-b8fa-9def4ba5c7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-col mt-5 tb:flex-row</value>
      <webElementGuid>2abfd0a2-d81d-4c03-b8fa-9def4ba5c7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YesNo</value>
      <webElementGuid>2abfd0a2-d81d-4c03-b8fa-9def4ba5c7d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
