<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_claimInformationSection</name>
   <tag></tag>
   <elementGuidId>b6423ca3-42cb-4a34-b4ac-5c28d9cfb286</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;flex\ flex-1\ tb\:flex-col\ mt-12\ px-5\ sm\:px-5\ tb\:px-10\ md\:px-10\ xl\:px-10\ lg\:px-10\ mb-10\ md\:w-3\/5\ lg\:w-3\/5\ xl\:w-3\/5&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '23Claim InformationClaim EventOutpatient...[truncated lines=74]' or . = '23Claim InformationClaim EventOutpatient...[truncated lines=74]')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:testid=[class=&quot;flex flex-1 tb:{{ip_address}}-{{ip_address}} mt-12 px-5 {{ip_address}}:px-10 xl:px-10 lg:px-10 mb-10 md:w-3/5 lg:w-3/5 xl:w-3/5&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_ngcontent-ng-c781028832</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-1 tb:flex-col mt-12 px-5 sm:px-5 tb:px-10 md:px-10 xl:px-10 lg:px-10 mb-10 md:w-3/5 lg:w-3/5 xl:w-3/5</value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>23Claim InformationClaim EventOutpatient...[truncated lines=74]</value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
