<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>label_creditDebitExpiry</name>
   <tag></tag>
   <elementGuidId>4bd32465-12f0-483c-98a5-5b76b17949b7</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-hospitalization-benetifs[1]/div[1]/div[2]/div[1]/esub-daterange-picker[1]/div[1]/div[1]/div[1]/div[2]/cds-calendar[1]/cds-calendar-header[1]/div[1]/section[2]/span[2]/label[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body:nth-of-type(1) > app-root:nth-of-type(1) > div:nth-of-type(1) > app-claim-information:nth-of-type(1) > app-submission-wizard:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(4) > app-hospitalization-benetifs:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(1) > esub-daterange-picker:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(2) > cds-calendar:nth-of-type(1) > cds-calendar-header:nth-of-type(1) > div:nth-of-type(1) > section:nth-of-type(2) > span:nth-of-type(2) > label:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'cds-body1 cds-demibold' and (text() = '2026' or . = '2026')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:text=&quot;{{credit_debit_expiry}}&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cds-body1 cds-demibold</value>
      <webElementGuid>2abfd0a2-d81d-4c03-b8fa-9def4ba5c7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2026</value>
      <webElementGuid>2abfd0a2-d81d-4c03-b8fa-9def4ba5c7d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
