<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>matSelect_language</name>
   <tag></tag>
   <elementGuidId>fbce9078-6d2f-40ed-8101-78c72c11e5f8</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-main-nav[1]/div[1]/div[1]/div[2]/app-language-switcher[1]/div[1]/div[1]/cds-dropdown[1]/mat-select[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.mat-mdc-select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Bahasa Indonesia' or . = 'Bahasa Indonesia') and @role = 'combobox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Bahasa Indonesia&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-select cds-body1 mat-mdc-select-empty ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5ac09ad8-769a-43b4-9158-eddcdd89760e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>5ac09ad8-769a-43b4-9158-eddcdd89760e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bahasa Indonesia</value>
      <webElementGuid>5ac09ad8-769a-43b4-9158-eddcdd89760e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
