<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>span_calendarMonthCell2</name>
   <tag></tag>
   <elementGuidId>3ce4d51d-6643-4fcb-aa2e-2d69e70ce5fd</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-hospitalization-benetifs[1]/div[1]/div[2]/div[1]/esub-daterange-picker[1]/div[1]/div[1]/div[1]/div[2]/cds-calendar[1]/div[1]/cds-calendar-year[1]/section[1]/cds-calendar-item[3]/span[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;cds-detail1\ cds-demibold\ cds-calendar-item\ cds-calendar-cell\ pill\ ng-star-inserted&quot;] > [class=&quot;cds-calendar-item__content&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Mar' or . = 'Mar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:testid=[class=&quot;cds-detail1 cds-demibold cds-calendar-item cds-calendar-cell pill ng-star-inserted&quot;s] >> internal:testid=[class=&quot;cds-calendar-item__content&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cds-calendar-item__content</value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mar</value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
