<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>span_calendarYearText</name>
   <tag></tag>
   <elementGuidId>320d6255-0904-4f99-b438-58a1ec622d44</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-hospitalization-benetifs[1]/div[1]/div[2]/div[1]/esub-daterange-picker[1]/div[1]/div[1]/div[1]/div[1]/cds-calendar[1]/div[1]/cds-calendar-multi-year[1]/section[4]/cds-calendar-item[2]/span[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.cds-calendar-multi-year > section:nth-of-type(4) > cds-calendar-item:nth-of-type(2) > [class=&quot;cds-calendar-item__content&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'cds-calendar-item__content' and (text() = '2025' or . = '2025')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section:nth-child(4) &gt; cds-calendar-item:nth-child(2) &gt; .cds-calendar-item__content >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cds-calendar-item__content</value>
      <webElementGuid>2abfd0a2-d81d-4c03-b8fa-9def4ba5c7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2025</value>
      <webElementGuid>2abfd0a2-d81d-4c03-b8fa-9def4ba5c7d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
