<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>span_calendarMonthCell</name>
   <tag></tag>
   <elementGuidId>1b661623-d9db-45ea-b4c0-616cb385b970</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/app-root[1]/div[1]/app-claim-information[1]/app-submission-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[4]/app-hospitalization-benetifs[1]/div[1]/div[2]/div[1]/esub-daterange-picker[1]/div[1]/div[1]/div[1]/div[1]/cds-calendar[1]/div[1]/cds-calendar-year[1]/section[1]/cds-calendar-item[2]/span[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section:nth-of-type(1) > cds-calendar-item:nth-of-type(2) > [class=&quot;cds-calendar-item__content&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Feb' or . = 'Feb')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>cds-calendar-item:nth-child(2) &gt; .cds-calendar-item__content >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cds-calendar-item__content</value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Feb</value>
      <webElementGuid>852bf310-1293-4d4e-99ed-9ef9da567f1b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
