<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_directTextOnParent</name>
   <tag></tag>
   <elementGuidId>d9633032-9032-4fe3-bdbf-a59a44c339d1</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.grid > div > div:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Direct text on parent
         
         Control case: the role element owns the text node directly, so text() should still work.
         
         role="option"
         ...[truncated lines=6]' or . = 'Direct text on parent
         
         Control case: the role element owns the text node directly, so text() should still work.
         
         role="option"
         ...[truncated lines=6]')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> nth=20</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-2xl border p-5 shadow-sm transition border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-900</value>
      <webElementGuid>5f6633c2-0476-47f7-b3a8-f7af77a8d63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Direct text on parent
      
      Control case: the role element owns the text node directly, so text() should still work.
      
      role="option"
      ...[truncated lines=6]</value>
      <webElementGuid>5f6633c2-0476-47f7-b3a8-f7af77a8d63d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
