<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_dienGiaDung</name>
   <tag></tag>
   <elementGuidId>20228d59-4625-4c06-b2a6-f1dba4a061d5</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/header[1]/div[1]/div[1]/div[2]/div[2]/div[1]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="sc-7ad7c877-1\ bbUcuP"] &gt; a:nth-of-type(1)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a &gt;&gt; internal:text=\"\u0111i\u1ec7n gia d\u1ee5ng\"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dien-gia-dung/c1882?from=header_keyword</value>
      <webElementGuid>149c0d05-27f8-40ae-b449-8ef421fa41dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>điện gia dụng</value>
      <webElementGuid>149c0d05-27f8-40ae-b449-8ef421fa41dd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
