<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_transferInfo</name>
   <tag></tag>
   <elementGuidId>30e127b5-c685-481a-b91b-62e9a47dec4c</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[6]/div[1]/div[1]/div[1]/article[1]/h3[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Mỹ có thể chuyển vũ khí dành cho {{address}} sang Trung Đông')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.article-topstory &gt; .title-news &gt; a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a &gt;&gt; internal:text="Mỹ có thể chuyển vũ khí dành cho {{address}} sang {{address}}"s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>{{url}}</value>
      <webElementGuid>729c1c9c-bc4b-4a6d-9590-7fe0836b023f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mỹ có thể chuyển vũ khí dành cho {{address}} sang {{address}} Đông</value>
      <webElementGuid>729c1c9c-bc4b-4a6d-9590-7fe0836b023f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mỹ có thể chuyển vũ khí dành cho {{address}} sang Trung Đông</value>
      <webElementGuid>729c1c9c-bc4b-4a6d-9590-7fe0836b023f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
