<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_phanTich</name>
   <tag></tag>
   <elementGuidId>4c91468f-f518-4bf6-9e97-14ba9cb09644</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[5]/div[1]/nav[1]/div[1]/div[2]/ul[1]/li[1]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Phân tích')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="ul-nav-folder\ parent"] &gt; li:nth-of-type(1) &gt; a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a[title="Phân tích"] &gt;&gt; nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/the-gioi/phan-tich</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phân tích</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Phân tích</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
