<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6c062b68-9cae-4a46-978c-3c3192402d1c</elementGuidId>
    <imagePath></imagePath>
    <name>link_itemBoTruong</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.article-topstory &gt; .title-news &gt; a</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/section[5]/div[1]/div[1]/div[1]/article[1]/h3[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Bộ trưởng Xây dựng: Cần sớm mở rộng trục nối {{address}} - {{address}} lên 12 làn')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"B\u1ed9 tr\u01b0\u1edfng X\u00e2y d\u1ef1ng: C\u1ea7n s\u1edbm m\u1edf r\u1ed9ng tr\u1ee5c n\u1ed1i {{address}} - {{address}} Th\u00e0nh l\u00ean 12 l\u00e0n\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Bộ trưởng Xây dựng: Cần sớm mở rộng trục nối {{address}} - {{address}} lên 12 làn</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Bộ trưởng Xây dựng: Cần sớm mở rộng trục nối {{address}} - {{address}} lên 12 làn</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
</WebElementEntity>