<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ab206f2b-1d35-4334-8bfd-20540474589d</elementGuidId>
    <imagePath></imagePath>
    <name>link_itemLoatMay</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>.content-art &gt; h4 &gt; a</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/section[7]/section[1]/div[1]/div[2]/div[1]/article[1]/div[2]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Loạt máy hút ẩm cho nhà chung cư dưới 100 m2')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Lo\u1ea1t m\u00e1y h\u00fat \u1ea9m cho nh\u00e0 chung c\u01b0 d\u01b0\u1edbi 100 m2\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>false</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Loạt máy hút ẩm cho nhà chung cư dưới 100 m2</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Loạt máy hút ẩm cho nhà chung cư dưới 100 m2</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
</WebElementEntity>