<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_kinhDoanh</name>
   <tag></tag>
   <elementGuidId>ff29a8ae-52f4-4434-8e11-c80aefe3b378</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/section[1]/nav[1]/ul[1]/li[6]/a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[equals(@title,'Kinh doanh')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.parent &gt; li:nth-of-type(6) &gt; a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>nav a[title="Kinh doanh"]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>{{url}}</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kinh doanh</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Kinh doanh</value>
      <webElementGuid>05784237-b012-49ec-bcf2-af94ad2fdce5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
