<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c8d3ee15-d0ba-4511-ae76-087ccfcab71c</elementGuidId>
    <imagePath></imagePath>
    <name>section_streamHome</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="section\ section_stream_home\ section_container"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/section[6]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>section:nth-child(12)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>section section_stream_home section_container</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Xung đột Trung Đông
        Iran cáo buộc Mỹ muốn 'chiếm đoạt dầu mỏ'
        
        Phát ngôn viên Bộ Ngoại giao Iran cáo buộc Mỹ đang tìm cách chia rẽ nước này nhằm chiếm đoạt nguồn tài nguyên dầu mỏ của Tehran. 
        
        ...[truncated lines=271]</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
</WebElementEntity>