<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e6302c34-d459-43fc-8e69-8945f23c9822</elementGuidId>
    <imagePath></imagePath>
    <name>section_photo</name>
    <selectorCollection>
        <entry>
            <key>CSS</key>
            <value>[class="section\ section_container\ section_photo"]</value>
        </entry>
        <entry>
            <key>XPATH</key>
            <value>//body/section[18]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>CSS</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>section:nth-child(25)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>section section_container section_photo</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Ảnh
        Người già, trẻ nhỏ hóa đại tướng, tiên nữ trong lễ hội Thổ Hà
        
        Trong lễ hội đón nhận bằng Di tích quốc gia đặc biệt, người dân đã hóa trang thành các vị tướng, ông {{name}} - {{name}}, tiên nữ..., sáng {{date_time}}
        
        ...[truncated lines=90]</value>
        <webElementGuid>c0ea916f-d8de-47a1-90c7-edc26b2981ef</webElementGuid>
    </webElementProperties>
</WebElementEntity>