<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>header_selectedTarget</name>
   <tag></tag>
   <elementGuidId>5310abea-2a93-42e1-aa7e-db7529cd375d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/div[3]/main[1]/div[1]/section[2]/aside[1]/div[1]/h2[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;space-y-5&quot;] [class=&quot;mb-3\ text-lg\ font-semibold\ text-gray-900\ dark\:text-white&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Selected target' or . = 'Selected target')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>h2 >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-3 text-lg font-semibold text-gray-900 dark:text-white</value>
      <webElementGuid>9eed9f35-3e58-4688-a784-767e12c46298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selected target</value>
      <webElementGuid>9eed9f35-3e58-4688-a784-767e12c46298</webElementGuid>
   </webElementProperties>
</WebElementEntity>
