<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_tikiVippromotion</name>
   <tag></tag>
   <elementGuidId>2ebfed49-5703-41d2-a6d2-89b705c126a3</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/main[1]/div[1]/div[1]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="sc-40be5443-1\ dDQfqa"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.sc-40be5443-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-40be5443-1 dDQfqa</value>
      <webElementGuid>149c0d05-27f8-40ae-b449-8ef421fa41dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TikiVIP Giảm 50%
      Đại Siêu Thị Online
      Hot Coupon Mỗi Ngày
      Tiki Trading
      Bắt Trend Làm Đẹp
      ...[truncated lines=1394]</value>
      <webElementGuid>149c0d05-27f8-40ae-b449-8ef421fa41dd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
