<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>div_quicklinks</name>
   <tag></tag>
   <elementGuidId>146c3a50-18c2-4b6f-994d-2c9801a83981</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/header[1]/div[1]/div[1]/div[2]/div[2]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class="sc-7ad7c877-1\ bbUcuP"]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.sc-7ad7c877-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-7ad7c877-1 bbUcuP</value>
      <webElementGuid>149c0d05-27f8-40ae-b449-8ef421fa41dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>điện gia dụng
      xe cộ
      mẹ &amp; bé
      khỏe đẹp
      nhà cửa
      ...[truncated lines=7]</value>
      <webElementGuid>149c0d05-27f8-40ae-b449-8ef421fa41dd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
